Hw 03 second part
Alex-Korzun/HW-03 pull request #2
Opened 2021-01-12 16:25 UTC by Alex-Korzun

2021-01-12 22:37 UTC, Likh-Alex approved these changes

2021-01-12 22:37 UTC, Likh-Alex commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +        return carDao.getById(id).orElseThrow();
I suggest to include a message inside `orElseThrow()`

2021-01-12 22:37 UTC, Likh-Alex commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +                        .contains(driverId))
we can simplify this block by using `anyMatch`  with predicate `car.getId().equals(driverId)` - meaning you filter only those `drivers` who have same `driverId`. This wrap up removes necessity to collect matched drivers.

2021-01-13 10:54 UTC, Sofasmile requested changes

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/dao/CarDao.java
> +    List<Car> getAllCars();
```suggestion
    List<Car> getAll();
```

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/dao/DriverDao.java
> +    List<Driver> getAllDrivers();
```suggestion
    List<Driver> getAll();
```

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/dao/impl/CarDaoImpl.java
> +        return Optional.ofNullable(Storage.cars.get(carId.intValue()));
чи правильно працює цей метод? чи завжди співпадає ід машини з її позицією в списку?

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +        return carDao.getById(id).orElseThrow();
```suggestion
        return carDao.getById(id).get();
```

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +        driverDao.create(driver);
давай вважати що driver уже э в БД

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +                        .contains(driverId))
```suggestion
                        .anyMatch(d -> d.getId().equals(driverId)))
```

2021-01-13 10:54 UTC, Sofasmile commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +    public List<Car> getAllByDriver(Long driverId) {
витягувати всі машини з БД на рівень сервісу - не зовсім коректна практика (можна пів БД витягнути в рантайм). Варто перенести цей метод на рівень дао

2021-01-13 11:13 UTC, Alex-Korzun commented on src/main/java/manufacturing/dao/CarDao.java
> +    List<Car> getAllCars();
done

2021-01-13 11:14 UTC, Alex-Korzun commented on src/main/java/manufacturing/dao/DriverDao.java
> +    List<Driver> getAllDrivers();
done

2021-01-13 11:18 UTC, Alex-Korzun commented on src/main/java/manufacturing/dao/impl/CarDaoImpl.java
> +        return Optional.ofNullable(Storage.cars.get(carId.intValue()));
cjanged it to `stream()`

2021-01-13 11:18 UTC, Alex-Korzun commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +        return carDao.getById(id).orElseThrow();
done

2021-01-13 11:23 UTC, Alex-Korzun commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +        driverDao.create(driver);
deleted creation

2021-01-13 11:24 UTC, Alex-Korzun commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +                        .contains(driverId))
changed

2021-01-13 11:31 UTC, Alex-Korzun commented on src/main/java/manufacturing/service/impl/CarServiceImpl.java
> +    public List<Car> getAllByDriver(Long driverId) {
done

2021-01-13 12:26 UTC, Sofasmile approved these changes

2021-01-13 12:32 UTC, merged